# Generated by Django 3.2.3 on 2021-06-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_hit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-create_dt',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
